# Generated by Django 5.0.2 on 2024-07-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipays', '0002_remove_userprofile_comment_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='zalo_key',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
