# Generated by Django 5.0.2 on 2024-07-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipays', '0003_alter_userprofile_zalo_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nickname',
            new_name='zalo_name',
        ),
    ]
